name: Java CI with GraalVM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'    # Ganti dari 'liberica' ke 'graalvm-ce'
          cache: maven

      - name: Verify GraalVM and native-image
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME:    $JAVA_HOME"
          java --version
          native-image --version

      - name: Build native executable (skip tests)
        run: mvn -B package --file pom.xml -DskipTests -Pnative
